---
version: "2.0"

services:
  web:
    image: fishflyhuang/sushiswap:latest
    expose:
      - port: 80
        as: 80
        to:
          - global: true

profiles:
  compute:
    web:
      resources:
        cpu:
          units: 1
        memory:
          size: 1Gi
        storage:
          size: 1Gi
  placement:
    westcoast:
      attributes:
        datacenter: equinix-metal-sjc1
        host: akash
        generation: mn2-ng
        host: akash
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
      pricing:
        web:
          denom: uakt
          amount: 100000

deployment:
  web:
    westcoast:
      profile: web
      count: 1
